[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "2.0.0"

[[constraint]]
  name = "github.com/mafredri/cdp"
  version = "0.16.4"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/alecthomas/chroma"
  version = "0.3.0"
